plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from

url           : "https://infominer.id/awesome-decentralized-id"
baseurl       : "awesome-decentralized-id"
title         : "Decentralized Identity"
description   : "Self-Sovereign, User-Owned and Controlled, Internet-Wide Identity."
author        : "⧉ Infominer"
logo          : "https://infominer.id/images/crypt0library.png"
repository    : "infominer33/awesome-decentralized-id"
github        : [metadata]

theme: jekyll-theme-modernist

twitter:
  title       : "Decentralized Identity"
  description : "Self-Sovereign, User-Owned and Controlled, Internet-Wide Identity."
  image       : "https://infominer.id/images/og-image.jpg"
  card        : "summary"
